import { Box, Image, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Box boxSize="sm">
          <Image src="/images/tracy.svg" alt="Logo" />
        </Box>
        <Text fontSize={"3xl"}>
          In Tracy we T<span style={{ color: "#f44a00" }}>rust</span>
        </Text>
        <Footer />
      </main>
    </div>
  );
};

export default Home;
