import { Button, Container, Heading, Input, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tracy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Heading paddingTop={2} paddingBottom={4}>
          Swap
        </Heading>
        <Container width="50%" gap="5px">
          <Input placeholder="Token In" />
          <Input placeholder="Token In" />
          <Input placeholder="Amount" />
          <Button>Swap</Button>
        </Container>
        <Text />
        <Footer />
      </main>
    </div>
  );
};

export default Home;
